schema_version: 1

context:
  name: mjml
  version: "0.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mjml-${{ version }}.tar.gz
  sha256: 614397e624b115d78f9064d0f8aabceda3b522785eca8c2818ee03ffa8fdbf37

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mjml  = mjml.scripts.mjml:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - beautifulsoup4
    - dotmap
    - docopt
    - jinja2

tests:
  - python:
      imports:
        - mjml
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - mjml --help

about:
  summary: Python implementation for MJML - a framework that makes responsive-email easy
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/FelixSchwarz/mjml-python

extra:
  recipe-maintainers:
    - thewchan
